version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/" # Location of package manifests
    target-branch: "dev" # Location of package manifests
    schedule:
      interval: "weekly"
